"""
**Traffik** - Distributed Rate Limiting for Starlette Applications.
"""

from ._locks import (
    AsyncLockAdapter,
    AsyncLockT,
    AsyncRLock,
    FairAsyncRLock,
    NamedLockHandle,
    NamedLockPool,
)
from ._utils import (
    CircuitBreaker,
    CircuitState,
    ProxyHeaders,
    get_remote_address,
    time,
)
from .backends import (
    InMemoryBackend,
    MultiProcessInMemoryBackend,
    ThrottleBackend,
    connection_throttled,
    default_identifier,
    get_throttle_backend,
)
from .config import (
    ANONYMOUS_IDENTIFIER,
    get_legacy_md5_keys,
    get_lock_blocking,
    get_lock_blocking_timeout,
    get_lock_ttl,
    set_legacy_md5_keys,
    set_lock_blocking,
    set_lock_blocking_timeout,
    set_lock_ttl,
)
from .headers import (
    DEFAULT_HEADERS_ALWAYS,
    DEFAULT_HEADERS_THROTTLED,
    Header,
    Headers,
)
from .rates import Rate
from .registry import (
    Bypass,
    Rule,
    ThrottleRegistry,
    bypass_if,
    throttle_if,
)
from .throttles import (
    HTTPThrottle,
    RequestThrottle,
    Throttle,
    ThrottleExceptionInfo,
    ThrottleStrategy,
    WebSocketThrottle,
    get_wait,
    is_throttled,
    throttled,
    websocket_throttled,
)
from .typing import (
    EXEMPTED,
    AsyncLock,
    ConnectionIdentifier,
    ConnectionThrottledHandler,
    Dependency,
    ExceptionHandler,
    HTTPConnectionT,
    HTTPConnectionTcon,
    LockConfig,
    Matchable,
    Network,
    Stringable,
    ThrottleErrorHandler,
    TrustedProxy,
    WaitPeriod,
)

__all__ = [
    "ANONYMOUS_IDENTIFIER",
    "DEFAULT_HEADERS_ALWAYS",
    "DEFAULT_HEADERS_THROTTLED",
    "EXEMPTED",
    "AsyncLock",
    "AsyncLockAdapter",
    "AsyncLockT",
    "AsyncRLock",
    "Bypass",
    "CircuitBreaker",
    "CircuitState",
    "ConnectionIdentifier",
    "ConnectionThrottledHandler",
    "Dependency",
    "ExceptionHandler",
    "FairAsyncRLock",
    "HTTPConnectionT",
    "HTTPConnectionTcon",
    "HTTPThrottle",
    "Header",
    "Headers",
    "InMemoryBackend",
    "LockConfig",
    "Matchable",
    "MultiProcessInMemoryBackend",
    "NamedLockHandle",
    "NamedLockPool",
    "Network",
    "ProxyHeaders",
    "Rate",
    "RequestThrottle",
    "Rule",
    "Stringable",
    "Throttle",
    "ThrottleBackend",
    "ThrottleErrorHandler",
    "ThrottleExceptionInfo",
    "ThrottleRegistry",
    "ThrottleStrategy",
    "TrustedProxy",
    "WaitPeriod",
    "WebSocketThrottle",
    "bypass_if",
    "connection_throttled",
    "default_identifier",
    "get_legacy_md5_keys",
    "get_lock_blocking",
    "get_lock_blocking_timeout",
    "get_lock_ttl",
    "get_remote_address",
    "get_throttle_backend",
    "get_wait",
    "is_throttled",
    "set_legacy_md5_keys",
    "set_lock_blocking",
    "set_lock_blocking_timeout",
    "set_lock_ttl",
    "throttle_if",
    "throttled",
    "time",
    "websocket_throttled",
]

__version__ = "1.3.0"
